import Head from 'next/head';
import { Container } from '@/Components/Container';
import { Typography } from '@/Components/Typography';
import { Input } from '@/Components/Input';
import { useForm } from 'react-hook-form';

export default function Home() {
  const { register, handleSubmit } = useForm();

  const onSubmit = (data) => {
    console.log(data);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Container
        as="main"
        width="100vw"
        height="100vh"
        flexDirection="column"
      >
        <Typography as="h1">Test</Typography>
        <form onSubmit={handleSubmit(onSubmit)}>
          <Input
            type="text"
            placeholder="Name"
            {...register('email')}
          />
        </form>
      </Container>
    </>
  );
}
