import Head from 'next/head';
import { Container } from '@/Components/UI/Container';
import { StyledWrapper } from '@/styles/Home.styles';
import journeyIllustration from '../../public/images/journey_illustration.jpg';
import Image from 'next/image';
import { SignupForm } from '@/Components/SignupForm';
import { FormSelector } from '@/Components/FormSelector';
import { useState } from 'react';
import { SigninForm } from '@/Components/SigninForm';
import { SIGNIN, SIGNUP } from '@/Constants/FormSelectors';
import { motion } from 'framer-motion';

export default function Home() {
  const [signupView, setSignupView] = useState(false);

  const spring = {
    type: 'spring',
    stiffness: 900,
    damping: 100,
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <StyledWrapper as="main">
        <Container
          width="40vw"
          height="60vh"
          display="grid"
          gridTemplateColumns="1fr 1fr"
          borderRadius="8px"
        >
          <Image
            alt="Image by vectorpocket on Freepik"
            src={journeyIllustration}
            fill
            style={{
              objectFit: 'cover',
              borderRadius: '8px',
              filter: 'brightness(60%)',
            }}
          />
          <motion.div
            layout
            transition={spring}
            style={{ order: signupView ? 2 : 1 }}
          >
            {signupView ? <SignupForm /> : <SigninForm />}
          </motion.div>
          <motion.div
            layout
            transition={spring}
            style={{ order: signupView ? 1 : 2 }}
          >
            {signupView ? (
              <FormSelector
                heading={SIGNIN.HEADING}
                subheading={SIGNIN.SUBHEADING}
                cta={SIGNIN.CTA}
                handleButtonClick={() => setSignupView((prev) => !prev)}
              />
            ) : (
              <FormSelector
                heading={SIGNUP.HEADING}
                subheading={SIGNUP.SUBHEADING}
                cta={SIGNUP.CTA}
                handleButtonClick={() => setSignupView((prev) => !prev)}
              />
            )}
          </motion.div>
        </Container>
      </StyledWrapper>
    </>
  );
}
