import Head from 'next/head';
import { Container } from '@/Components/UI/Container';
import { useForm } from 'react-hook-form';
import { StyledWrapper } from '@/styles/Home.styles';
import journeyIllustration from '../../public/images/journey_illustration.jpg';
import Image from 'next/image';
import { SignupForm } from '@/Components/SignupForm';
import { FormSelector } from '@/Components/FormSelector';
import { useState } from 'react';
import { Typography } from '@/Components/UI/Typography';
import { Button } from '@/Components/UI/Button';
import { SigninForm } from '@/Components/SigninForm';

export default function Home() {
  const [signupView, setSignupView] = useState(false);
  const { register, handleSubmit } = useForm();

  const onSubmit = (data) => {
    console.log(data);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <StyledWrapper as="main">
        <Container height="40vh">
          <Image
            alt="Image by vectorpocket on Freepik"
            src={journeyIllustration}
            fill
            style={{
              objectFit: 'cover',
              borderRadius: '8px',
              zIndex: '1',
            }}
          />
          {signupView ? <SignupForm /> : <SigninForm />}
          {signupView ? (
            <FormSelector>
              <Typography as="h3">Already have an account?</Typography>
              <Typography>Sign in to continue your journey</Typography>
              <Button onClick={() => setSignupView((prev) => !prev)}>
                Sign in
              </Button>
            </FormSelector>
          ) : (
            <FormSelector>
              <Typography as="h3">Start your journey now</Typography>
              <Typography>
                Don&apos;t have an account yet? Join us now and start your
                journey today!
              </Typography>
              <Button onClick={() => setSignupView((prev) => !prev)}>
                Sign up
              </Button>
            </FormSelector>
          )}
        </Container>
      </StyledWrapper>
    </>
  );
}
